services:
  - type: web
    name: ecommerce-frontend
    rootDir: E-Commerse
    env: node
    plan: free
    buildCommand: npm install && npm run build
    startCommand: npm run preview
    envVars:
      - key: NODE_VERSION
        value: 20.18.0
